### ISSUE TITLE
Fix spacing between index and links in the table of urls under PythonNet 

### ISSUE THREAD

**Issue by annp89** [realpython/python-guide#566]
The spacing between the list item number and the url seems inconsistent in the table of links
(http://docs.python-guide.org/en/latest/starting/which-python/#pythonnet)

I think the fix can be as simple as setting the `width` to a specific pixel size  `12px` (appears to work) here
https://github.com/kennethreitz/python-guide/blob/master/docs/_themes/kr/static/flasky.css_t#L309

Thoughts? I'd be happy to open a pull request with that change.

**Comment by sigmavirus24** [comment]
I wonder if this is "fixed"/"better" with the default alabaster theme.

**Comment by annp89** [comment]
Same issue in the references here http://docs.python-guide.org/en/latest/scenarios/web/#chameleon

**Comment by sigmavirus24** [comment]
@annp89 those are all footnote sections. Are there other *non-footnote* tables that are displayed like this? I think this styling is intentional.

**Comment by Hasimir** [comment]
Footnotes have always been a bit iffy in HTML with pretty much every different group who weighed in on it coming up with their own solution.  It's not as structured or as strict as XML or SGML, so there will always be inconsistencies.  Which is why this same page can end up with a fifth footnote referenced from the top, but appended at the bottom (because someone couldn't be bothered renumbering the whole page or edited a subsection and didn't know about the rest).

I think you'll find that in most cases each footnote is a separate paragraph for a start and other variations will exist depending on whether or not people intended to try to make them look like in print footnotes they're used to.  It's also worth remembering that things like footnotes were left out of HTML because it had the ability to link directly to source material rather than rely on footnotes (that was kinda the point).  The theory being that printed books requiring more explicit typesetting would use some other content standard (e.g. [DocBook](http://docbook.org), which includes both footnote and footnoteref elements).

Meanwhile reStructuredText, for all its awesomeness, is still limited to some degree by what it tries to simplify and have "just work" in text.  The Python Guide sacrifices some typographical aspects in order to allow for ease of adding content by a wider variety of contributors, because reST isn't much more difficult to learn than Markdown and the same can't be said for specialist XML schemas like Schematron, Relax NG and the host that follows, let alone specific implementations like DocBook or [DITA](http://dita.xml.org/) (both of which are extremely good, but using them would pretty much guarantee a massive reduction in the number of contributors to the book (like around 99%).

**Comment by sigmavirus24** [comment]
@Hasimir how does that relate to the styling of the tables in which the footnote references are displayed?

**Comment by annp89** [comment]
@sigmavirus24 I havent seen non-footnote sections displayed like that. I agree, it may be intentional.

And @Hasimir I echo the sane question @sigmavirus24  asked

**Comment by sigmavirus24** [comment]
@annp89 is there perhaps a good way to distinguish the footnote sections without making them look too much like non-footnote tables that would be perhaps better styled?

**Comment by TridevGuha** [comment]
I have committed a PR https://github.com/kennethreitz/python-guide/pull/639

**Comment by apjanke** [comment]
Looks like this got fixed by #618?
