### ISSUE TITLE
Inclusion of Pyenv

### ISSUE THREAD

**Issue by supermensa** [realpython/python-guide#765]
Please add pyenv to the guide, it has greatly simplified managing versions of Python for me.
[https://github.com/yyuu/pyenv](https://github.com/yyuu/pyenv)

**Comment by obestwalter** [comment]
Also see: #395 pyenv is great :)

**Comment by obestwalter** [comment]
Also see: https://github.com/kennethreitz/python-guide/pull/402

**Comment by obestwalter** [comment]
Also see: #728 (I really don't want to be annoying ... I just would like to point out that pyenv is actually state of the art on Unix/Linux and it would be nice if this would be acknowledged in this guide).

**Comment by userlerueda** [comment]
I think this has been integrated and can be found [here](http://docs.python-guide.org/en/latest/dev/env/#pyenv). @obestwalter @supermensa do you think that it is enough and that this issue can be closed?

**Comment by generalandrew** [comment]
@userlerueda I would recommend including it as part of the [installation instructions](http://docs.python-guide.org/en/latest/starting/install/osx/). 

For newbies it would make more literal sense to have the installation command for python be `pyenv install 2.7.8` for version 2.7.8 instead of `brew python` and it automagically picking `version 2.7`. I'd also think that this is more of a future proof when/if homebrew decides `brew python` => `version 3`.

**Comment by obestwalter** [comment]
> I'd also think that this is more of a future proof when/if homebrew decides brew python => version 3.

That recently happened, if am not mistaken.
